### ISSUE TITLE
[mac] Product cannot start

### ISSUE THREAD

**Issue by kthoms** [Yakindu/solidity-ide#63]
The built product does not launch on Mac.
```
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
        ...
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
        ...
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.200.v20170724-0836

java.lang.NoClassDefFoundError: javax/annotation/PreDestroy
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
        ...
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.200.v20170724-0836
```

Full log: [log.txt](https://github.com/andreasmuelder/solidity-ide/files/1517068/log.txt)

**Comment by nyssen** [comment]
Have you added a -vm statement to the .ini?
Unless specified there, Eclipse might pick another (higher) vm.
